
import{initializeApp}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";import{getAuth,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";import{getFirestore,collection,getDocs,doc,updateDoc,deleteDoc}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";import * as d3 from "https://cdn.jsdelivr.net/npm/d3@7/+esm";import {feature as topoFeature} from "https://cdn.jsdelivr.net/npm/topojson-client@3/+esm";
const firebaseConfig={apiKey:"AIzaSyAKxQdUM49cVbBaXWJ5DF3s7EaNKlJRGhA",authDomain:"login-dingloft.firebaseapp.com",projectId:"login-dingloft",storageBucket:"login-dingloft.firebasestorage.app",messagingSenderId:"549466738202",appId:"1:549466738202:web:8bf305fe2c753e9d76cba3",measurementId:"G-R9SGZCDN13"};
const WORKER="https://autumn-breeze-dfa0.evolutiongt01.workers.dev";const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);const ADMIN=new Set(["evolutiongt01@gmail.com","tepaz2025@gmail.com","matzarcesar01@hotmail.com"]);let products=[],multitracks=[],orders=[],customers=[],reviews=[],reservations=[],presenceSessions=[],editingSku="",editingMultitrackId="",activeOrder=null,activeCustomer=null,activeGhost=null;const DEFAULT_REVIEW_MESSAGE="Tu cuenta está temporalmente en revisión. Hemos recibido un reporte relacionado con una transacción o posible actividad irregular y nuestro equipo está verificando la información. Durante esta revisión, el acceso a la cuenta y a sus funciones permanece suspendido. Si consideras que se trata de un error, comunícate con Soporte Dingloft.";
let introHidden=false;function hideAdminIntro(){if(introHidden)return;introHidden=true;const el=document.getElementById('adminIntro');document.body.classList.add('admin-ready');el?.classList.add('hide');setTimeout(()=>el?.remove(),650)}setTimeout(()=>hideAdminIntro(),5000);
function decorateMobileTables(){document.querySelectorAll('.table-wrap table').forEach(table=>{const labels=[...table.querySelectorAll('thead th')].map(th=>th.textContent.trim());table.querySelectorAll('tbody tr').forEach(tr=>{[...tr.children].forEach((td,i)=>{if(td.tagName==='TD')td.dataset.label=labels[i]||''})})})}
const tableObserver=new MutationObserver(()=>requestAnimationFrame(decorateMobileTables));tableObserver.observe(document.body,{childList:true,subtree:true});window.addEventListener('resize',()=>requestAnimationFrame(decorateMobileTables));

const $=id=>document.getElementById(id),esc=s=>String(s??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),money=n=>`$${Number(n||0).toFixed(2)}`,date=v=>{if(!v)return"—";const d=new Date(v);return isNaN(d)?"—":d.toLocaleString("es-GT",{dateStyle:"medium",timeStyle:"short"})},flag=code=>{code=String(code||"").toUpperCase();return/^[A-Z]{2}$/.test(code)?String.fromCodePoint(...[...code].map(c=>127397+c.charCodeAt(0))):"🌐"},slug=s=>String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,80);
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2800)}function status(id,t,type=""){$(id).textContent=t;$(id).className=`statusmsg ${type}`}
async function api(path,{method="GET",body}={}){
  const u=auth.currentUser;if(!u)throw Error("Sesión no válida");
  const run=async(forceRefresh=false)=>{
    const token=await u.getIdToken(forceRefresh);
    const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);
    let r;
    try{r=await fetch(WORKER+path,{method,signal:controller.signal,cache:"no-store",headers:{Authorization:`Bearer ${token}`,...(body?{"content-type":"application/json"}:{})},body:body?JSON.stringify(body):undefined})}
    catch(networkError){const e=Error(networkError?.name==="AbortError"?"El Worker tardó demasiado en responder":"No se pudo conectar con el Worker");e.status=0;e.path=path;throw e}
    finally{clearTimeout(timer)}
    const d=await r.json().catch(()=>({}));
    if(!r.ok||d.ok===false){const e=Error(d.error||`Error ${r.status}`);e.status=r.status;e.code=d.code||"";e.path=path;throw e}
    return d;
  };
  try{return await run(false)}catch(e){if(e.status===401||e.status===403){try{return await run(true)}catch(retry){throw retry}}throw e}
}
function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));const target=$(`view-${name}`);if(!target)return;target.classList.add('active');document.querySelectorAll('.nav button[data-view],.mobile-admin-nav button[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('crumb').textContent={dashboard:'Resumen',orders:'Pedidos',products:'Productos',multitracks:'Multitracks',customers:'Clientes',ghosts:'Fantasmas',reviews:'Reseñas',finance:'Finanzas',reservations:'Reservas'}[name]||name;history.replaceState(null,'',`#${name}`);window.scrollTo({top:0,behavior:'smooth'});const active=document.querySelector(`.mobile-admin-nav button[data-view="${name}"]`);active?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'});decorateMobileTables()}document.querySelectorAll('.nav button[data-view],.mobile-admin-nav button[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll('[data-goto]').forEach(b=>b.onclick=()=>showView(b.dataset.goto));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).classList.remove('show'));document.querySelectorAll('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)m.classList.remove('show')});
const loadErrors={};
async function guardedLoad(key,fn){try{await fn();delete loadErrors[key];return{key,ok:true}}catch(error){loadErrors[key]=error;console.error(`[Admin ${key}]`,error);return{key,ok:false,error}}}
function renderSyncHealth(){const box=$('adminSyncHealth');if(!box)return;const entries=Object.entries(loadErrors);if(!entries.length){box.classList.remove('show','auth');return}box.classList.add('show');const authProblem=entries.some(([,e])=>Number(e?.status)===401||Number(e?.status)===403);box.classList.toggle('auth',authProblem);$('adminSyncTitle').textContent=authProblem?'El Worker rechazó parte del panel':'Algunos módulos no pudieron sincronizar';$('adminSyncText').textContent=entries.map(([k,e])=>`${({products:'Productos',multitracks:'Multitracks',orders:'Pedidos',customers:'Clientes',presence:'Presencia',reviews:'Reseñas',reservations:'Reservas'}[k]||k)}: ${e?.message||'error'}`).join(' · ');$('adminSyncHint').textContent=authProblem?'Si estás usando matzarcesar01@hotmail.com, confirma que el Worker desplegado también tenga ese correo en ADMIN_EMAILS. Los demás módulos seguirán cargando por separado.':'El panel ya no se pone todo en cero por un solo fallo. Pulsa Actualizar para reintentar.'}
async function loadAll(){
  const jobs=[['products',loadProducts],['multitracks',loadMultitracks],['orders',loadOrders],['customers',loadCustomers],['presence',loadPresence],['reviews',loadReviews],['reservations',loadReservations]];
  const tasks=jobs.map(([key,fn])=>guardedLoad(key,fn).then(result=>{
    renderDashboard();renderFinance();renderClientGlobe();renderSyncHealth();decorateMobileTables();return result;
  }));
  const results=await Promise.all(tasks);
  renderDashboard();renderFinance();renderClientGlobe();renderSyncHealth();decorateMobileTables();
  return results;
}
function renderDashboard(){const paid=orders.filter(o=>o.paymentStatus==='paid'),rev=paid.reduce((s,o)=>s+Number(o.amountPaidUsd||0),0),active=products.filter(p=>p.active!==false),missing=active.filter(p=>!p.deliveryConfigured);$('dOrders').textContent=loadErrors.orders?'—':paid.length;$('dRevenue').textContent=loadErrors.orders?'—':money(rev);$('dCustomers').textContent=loadErrors.customers?'—':customers.length;$('dProducts').textContent=loadErrors.products?'—':active.length;$('dMissing').textContent=loadErrors.products?'Sin sincronizar':`${missing.length} sin entrega`;$('recentOrders').innerHTML=loadErrors.orders?`<div class="empty">${esc(loadErrors.orders.message||'No se pudieron cargar los pedidos.')}</div>`:orders.slice(0,6).map(o=>`<div style="display:flex;justify-content:space-between;gap:12px;padding:10px 0;border-bottom:1px solid rgba(255,255,255,.05)"><div><b>${esc(o.orderNumber)}</b><div class="muted" style="font-size:11px;margin-top:3px">${esc(o.userEmail)} · ${(o.items||[]).map(i=>esc(i.name)).join(', ')}</div></div><b>${money(o.amountPaidUsd)}</b></div>`).join('')||'<div class="empty">Todavía no hay pedidos.</div>';$('catalogAlerts').innerHTML=loadErrors.products?`<div class="alert"><b>Catálogo sin sincronizar</b><br>${esc(loadErrors.products.message||'No se pudo consultar el catálogo.')}</div>`:missing.length?missing.slice(0,10).map(p=>`<div class="alert"><b>${esc(p.name)}</b><br>Falta link de descarga. El checkout permanece bloqueado.</div>`).join(''):'<div class="pill ok"><i class="bi bi-check-circle"></i> Todo el catálogo activo tiene entrega</div>'}


// --- Globe / recent customer locations ---
const COUNTRY_COORDS={GT:[15.78,-90.23],US:[39.5,-98.35],MX:[23.63,-102.55],CA:[56.13,-106.35],SV:[13.79,-88.9],HN:[15.2,-86.24],NI:[12.87,-85.21],CR:[9.75,-83.75],PA:[8.54,-80.78],BZ:[17.19,-88.5],DO:[18.74,-70.16],PR:[18.22,-66.59],CU:[21.52,-77.78],JM:[18.11,-77.3],CO:[4.57,-74.3],VE:[6.42,-66.59],EC:[-1.83,-78.18],PE:[-9.19,-75.02],BO:[-16.29,-63.59],CL:[-35.68,-71.54],AR:[-38.42,-63.62],UY:[-32.52,-55.77],PY:[-23.44,-58.44],BR:[-14.24,-51.93],GB:[55.38,-3.44],ES:[40.46,-3.75],FR:[46.23,2.21],DE:[51.17,10.45],IT:[41.87,12.57],PT:[39.4,-8.22],NL:[52.13,5.29],BE:[50.5,4.47],CH:[46.82,8.23],AT:[47.52,14.55],IE:[53.14,-7.69],SE:[60.13,18.64],NO:[60.47,8.47],DK:[56.26,9.5],FI:[61.92,25.75],PL:[51.92,19.15],CZ:[49.82,15.47],RO:[45.94,24.97],GR:[39.07,21.82],TR:[38.96,35.24],RU:[61.52,105.32],UA:[48.38,31.17],IL:[31.05,34.85],SA:[23.89,45.08],AE:[23.42,53.85],EG:[26.82,30.8],MA:[31.79,-7.09],ZA:[-30.56,22.94],NG:[9.08,8.68],KE:[-0.02,37.91],IN:[20.59,78.96],PK:[30.38,69.35],BD:[23.68,90.36],CN:[35.86,104.2],JP:[36.2,138.25],KR:[35.91,127.77],ID:[-0.79,113.92],PH:[12.88,121.77],TH:[15.87,100.99],VN:[14.06,108.28],MY:[4.21,101.98],SG:[1.35,103.82],AU:[-25.27,133.78],NZ:[-40.9,174.89]};

const GLOBE_DATA_URL="https://cdn.jsdelivr.net/npm/world-atlas@2/land-110m.json";
let globeRAF=0,globeHotspots=[],worldLand=null,worldLandPromise=null;
const globeState={rotation:[25,-12,0],dragging:false,lastPointer:null,lastInteraction:0,autoSpin:true};
function ensureWorldLand(){
  if(worldLand) return Promise.resolve(worldLand);
  if(worldLandPromise) return worldLandPromise;
  worldLandPromise=fetch(GLOBE_DATA_URL,{cache:'force-cache'}).then(r=>{if(!r.ok) throw new Error('No se pudo descargar la geografía del globo');return r.json()}).then(topo=>{worldLand=topoFeature(topo,topo.objects.land);return worldLand}).catch(err=>{console.error('Globo Dingloft:',err);worldLand=null;return null});
  return worldLandPromise;
}
function recentCustomers(){return customers.slice().sort((a,b)=>{const ta=new Date(a.lastPurchaseAt||a.lastLogin||0).getTime()||0,tb=new Date(b.lastPurchaseAt||b.lastLogin||0).getTime()||0;return tb-ta}).slice(0,8)}
function sessionDeviceLabel(p){return String(p?.device||p?.lastPresenceDevice||'Web').trim()||'Web'}
function sessionBrowserLabel(p){return String(p?.browser||p?.lastPresenceBrowser||'Sin navegador').trim()||'Sin navegador'}
function deviceIconClass(label=''){const x=String(label).toLowerCase();if(x.includes('iphone'))return 'bi-phone';if(x.includes('ipad'))return 'bi-tablet';if(x.includes('android'))return x.includes('tablet')?'bi-tablet':'bi-phone';if(x.includes('mac'))return 'bi-laptop';if(x.includes('windows')||x.includes('pc')||x.includes('linux'))return 'bi-display';return 'bi-globe2'}
function browserIconClass(label=''){const x=String(label).toLowerCase();if(x.includes('chrome'))return 'bi-browser-chrome';if(x.includes('safari'))return 'bi-compass';if(x.includes('edge'))return 'bi-browser-edge';if(x.includes('firefox'))return 'bi-browser-firefox';if(x.includes('opera'))return 'bi-browser-chrome';return 'bi-globe2'}
function sessionDeviceGlyph(label=''){const x=String(label).toLowerCase();if(x.includes('iphone')||x.includes('android')||x.includes('phone'))return '📱';if(x.includes('ipad')||x.includes('tablet'))return '📟';if(x.includes('mac')||x.includes('windows')||x.includes('linux')||x.includes('pc'))return '💻';return '🌐'}
function sessionDeviceMeta(p){const mode=p?.standalone?'App instalada':'Navegador web';const browser=sessionBrowserLabel(p);return `${mode} · ${browser}`}
function geoPill(kind,label){return `<span class="geo-mini-pill ${kind==='browser'?'browser':''}"><i class="bi ${kind==='browser'?browserIconClass(label):deviceIconClass(label)}"></i>${esc(label)}</span>`}
function presenceDisplayName(p){return p.displayName||String(p.email||'').split('@')[0]||(p.authenticated?'Cliente Dingloft':'Fantasma')}
function presencePlace(p){const g=p.geo||{};return [g.city,g.region,g.country].filter(Boolean).filter((x,i,a)=>a.indexOf(x)===i).join(', ')||'Ubicación aproximada sin nombre'}
function renderClientLocationList(){
  const root=$('recentClientLocations'); if(!root) return;
  const live=livePresence(),recent=recentPresence();
  const badge=document.querySelector('.geo-live'); if(badge) badge.textContent=live.length?`${live.length} conectado${live.length===1?'':'s'}`:'Sin clientes activos';
  const label=document.querySelector('.geo-list-label'); if(label) label.textContent='Actividad en vivo y reciente';
  if(recent.length){
    $('geoCoverage').textContent=`${live.length} en línea · ${recent.length} recientes`;
    root.innerHTML=recent.map(p=>{const place=presencePlace(p),name=presenceDisplayName(p),who=p.email||p.path||'Sesión web';const device=sessionDeviceLabel(p),browser=sessionBrowserLabel(p),online=p.online===true;return `<div class="geo-client"><div class="geo-avatar">${online?'🟢':sessionDeviceGlyph(device)}</div><div class="geo-copy"><b>${esc(name)}</b><small>${esc(place)}</small><div class="geo-badges">${geoPill('device',device)}${geoPill('browser',browser)}</div><small>${esc(who)}</small></div><div class="geo-time"><b>${online?'En línea':'Reciente'}</b><small>${date(p.lastSeenAt)}</small></div></div>`}).join('');
    return;
  }
  if(loadErrors.presence){root.innerHTML=`<div class="geo-empty">${esc(loadErrors.presence.message||'No se pudo cargar presencia en vivo.')}</div>`;$('geoCoverage').textContent='Presencia sin sincronizar';return}
  const list=recentCustomers(); const located=list.filter(c=>COUNTRY_COORDS[String(c.nationalityCode||'').toUpperCase()]);
  $('geoCoverage').textContent=`${located.length} de ${list.length} ubicaciones históricas`;
  root.innerHTML=list.length?list.map(c=>{const code=String(c.nationalityCode||'').toUpperCase();const photo=String(c.photoURL||'').trim();const name=c.displayName||String(c.email||'Cliente').split('@')[0];const when=c.lastPurchaseAt||c.lastLogin;const device=String(c.lastPresenceDevice||'Sin actividad reciente');const browser=String(c.lastPresenceBrowser||'Sin navegador');return `<div class="geo-client"><div class="geo-avatar">${photo?`<img src="${esc(photo)}" alt="">`:flag(code)}</div><div class="geo-copy"><b>${esc(name)}</b><small>${flag(code)} ${esc(c.nationality||'Ubicación sin registrar')} · ${esc(c.email||'')}</small><div class="geo-badges">${geoPill('device',device)}${geoPill('browser',browser)}</div></div><div class="geo-time"><b>${Number(c.ordersCount||0)} compra${Number(c.ordersCount||0)===1?'':'s'}</b><small>${date(when)}</small></div></div>`}).join(''):'<div class="geo-empty">Todavía no hay clientes para mostrar.</div>'
}
function activeGlobeSources(){
  const liveSources=recentPresence().filter(x=>Number.isFinite(Number(x?.geo?.latitude))&&Number.isFinite(Number(x?.geo?.longitude)));
  if(liveSources.length) return liveSources.map((p,index)=>({lat:Number(p.geo.latitude),lon:Number(p.geo.longitude),online:p.online===true,index,kind:p.ghost===true?'ghost':'presence',name:presenceDisplayName(p),place:presencePlace(p),device:sessionDeviceLabel(p),browser:sessionBrowserLabel(p),when:p.lastSeenAt,who:p.email||p.path||'Sesión web'}));
  return recentCustomers().map((c,index)=>{const co=COUNTRY_COORDS[String(c.nationalityCode||'').toUpperCase()]; if(!co) return null; return {lat:co[0],lon:co[1],online:false,index,kind:'customer',name:c.displayName||String(c.email||'Cliente').split('@')[0],place:c.nationality||'Ubicación sin registrar',device:String(c.lastPresenceDevice||'Sin actividad reciente'),browser:String(c.lastPresenceBrowser||'Sin navegador'),when:c.lastPurchaseAt||c.lastLogin,who:c.email||'Cuenta histórica'}}).filter(Boolean)
}
function positionGlobeTooltip(marker,canvas){
  const tip=$('globeTooltip'); if(!tip||!canvas||!marker) return; const rect=canvas.getBoundingClientRect(); const wrap=canvas.parentElement.getBoundingClientRect();
  tip.innerHTML=`<b>${esc(marker.name)}</b><small>${esc(marker.place)}</small><div class="tip-row">${geoPill('device',marker.device)}${geoPill('browser',marker.browser)}</div><small>${marker.online?'En línea ahora':'Última actividad'} · ${date(marker.when)}</small>`;
  const left=(rect.left-wrap.left)+marker.x, top=(rect.top-wrap.top)+marker.y-12;
  tip.style.left=`${left}px`; tip.style.top=`${top}px`; tip.classList.add('show');
}
function hideGlobeTooltip(){const tip=$('globeTooltip'); if(tip) tip.classList.remove('show')}
function visibleMarker(center,m){
  if(!center) return true;
  return d3.geoDistance([m.lon,m.lat],center)<=(Math.PI/2)-0.01;
}
function drawGlobeBase(ctx,projection,w,h,cx,cy,r){
  const path=d3.geoPath(projection,ctx);
  ctx.save();
  const aura=ctx.createRadialGradient(cx,cy,r*.68,cx,cy,r*1.18);
  aura.addColorStop(0,'rgba(56,174,255,.07)');
  aura.addColorStop(.58,'rgba(37,124,214,.06)');
  aura.addColorStop(1,'rgba(0,0,0,0)');
  ctx.fillStyle=aura; ctx.fillRect(0,0,w,h);
  ctx.beginPath(); path({type:'Sphere'}); ctx.save(); ctx.clip();
  const ocean=ctx.createRadialGradient(cx-r*.34,cy-r*.36,r*.08,cx,cy,r*1.02);
  ocean.addColorStop(0,'#173d63');
  ocean.addColorStop(.22,'#0c2f53');
  ocean.addColorStop(.55,'#081f39');
  ocean.addColorStop(.82,'#06172b');
  ocean.addColorStop(1,'#040f1e');
  ctx.fillStyle=ocean; ctx.fillRect(cx-r-4,cy-r-4,r*2+8,r*2+8);
  ctx.beginPath(); path(d3.geoGraticule10()); ctx.strokeStyle='rgba(149,214,255,.12)'; ctx.lineWidth=.65; ctx.stroke();
  if(worldLand){
    ctx.beginPath(); path(worldLand); ctx.fillStyle='rgba(167,182,196,.86)'; ctx.shadowColor='rgba(192,228,255,.15)'; ctx.shadowBlur=12; ctx.fill(); ctx.shadowBlur=0;
    ctx.beginPath(); path(worldLand); ctx.strokeStyle='rgba(233,245,255,.18)'; ctx.lineWidth=.7; ctx.stroke();
  }
  ctx.restore();
  ctx.beginPath(); path({type:'Sphere'}); ctx.lineWidth=1.15; ctx.strokeStyle='rgba(116,210,255,.35)'; ctx.stroke();
  ctx.beginPath(); path({type:'Sphere'}); ctx.lineWidth=8; ctx.strokeStyle='rgba(28,150,255,.09)'; ctx.stroke();
  ctx.restore();
}
function bindGlobeInteractions(){
  const canvas=$('clientGlobe'); if(!canvas||canvas.dataset.bound==='1') return; canvas.dataset.bound='1';
  const pick=(x,y)=>{let hit=null,dist=1e9; globeHotspots.forEach(m=>{const d=Math.hypot(m.x-x,m.y-y); if(d<m.hit&&d<dist){dist=d; hit=m}}); return hit};
  canvas.addEventListener('pointerdown',e=>{globeState.dragging=true;globeState.autoSpin=false;globeState.lastPointer={x:e.clientX,y:e.clientY};canvas.setPointerCapture?.(e.pointerId);canvas.style.cursor='grabbing';hideGlobeTooltip()});
  canvas.addEventListener('pointermove',e=>{
    const r=canvas.getBoundingClientRect(); const x=e.clientX-r.left,y=e.clientY-r.top;
    if(globeState.dragging&&globeState.lastPointer){
      const dx=e.clientX-globeState.lastPointer.x, dy=e.clientY-globeState.lastPointer.y;
      globeState.rotation[0]+=dx*.35;
      globeState.rotation[1]=Math.max(-70,Math.min(70,globeState.rotation[1]-dy*.35));
      globeState.lastPointer={x:e.clientX,y:e.clientY};
      globeState.lastInteraction=Date.now();
      hideGlobeTooltip();
      return;
    }
    const hit=pick(x,y); if(hit) positionGlobeTooltip(hit,canvas); else hideGlobeTooltip();
  });
  const stopDrag=()=>{globeState.dragging=false;globeState.lastPointer=null;canvas.style.cursor='grab'};
  canvas.addEventListener('pointerup',stopDrag); canvas.addEventListener('pointercancel',stopDrag); canvas.addEventListener('pointerleave',()=>{if(!globeState.dragging) hideGlobeTooltip()});
  canvas.addEventListener('dblclick',()=>{globeState.rotation=[25,-12,0];globeState.autoSpin=true;globeState.lastInteraction=0;hideGlobeTooltip()});
}
function drawClientGlobe(ts=performance.now()){
  const canvas=$('clientGlobe'); if(!canvas) return; bindGlobeInteractions(); ensureWorldLand();
  const rect=canvas.getBoundingClientRect(); const dpr=Math.min(window.devicePixelRatio||1,2); const w=Math.max(180,rect.width||315),h=Math.max(180,rect.height||315); const rw=Math.round(w*dpr),rh=Math.round(h*dpr); if(canvas.width!==rw||canvas.height!==rh){canvas.width=rw;canvas.height=rh}
  const ctx=canvas.getContext('2d'); ctx.setTransform(dpr,0,0,dpr,0,0); ctx.clearRect(0,0,w,h);
  const cx=w*.5,cy=h*.5,r=Math.min(w,h)*.455;
  if(globeState.autoSpin&&!globeState.dragging&&(Date.now()-globeState.lastInteraction>2200)) globeState.rotation[0]+=0.045;
  const projection=d3.geoOrthographic().translate([cx,cy]).scale(r).rotate(globeState.rotation).clipAngle(90).precision(.3);
  drawGlobeBase(ctx,projection,w,h,cx,cy,r);
  const center=projection.invert([cx,cy]);
  const markers=[];
  activeGlobeSources().forEach((m,index)=>{const pos=projection([m.lon,m.lat]); if(!pos||!visibleMarker(center,m)) return; markers.push({...m,x:pos[0],y:pos[1],index:m.index??index})});
  globeHotspots=[];
  markers.sort((a,b)=>a.lat-b.lat).forEach(m=>{
    const pulse=1+Math.sin(ts/(m.online?280:440)+m.index*1.35)*(m.online?.2:.11);
    const core=m.online?4.6:4.0, aura=(m.online?16:12.5)*pulse;
    ctx.beginPath(); ctx.arc(m.x,m.y,aura,0,Math.PI*2); ctx.fillStyle=m.online?'rgba(74,245,184,.16)':'rgba(79,215,255,.12)'; ctx.fill();
    ctx.beginPath(); ctx.arc(m.x,m.y,core*pulse*.9,0,Math.PI*2); ctx.fillStyle=m.online?'rgba(124,255,206,.98)':'rgba(140,234,255,.98)'; ctx.shadowColor=m.online?'rgba(70,255,183,.95)':'rgba(66,220,255,.95)'; ctx.shadowBlur=m.online?22:18; ctx.fill(); ctx.shadowBlur=0;
    ctx.beginPath(); ctx.arc(m.x,m.y,(core+5.5)*pulse,0,Math.PI*2); ctx.strokeStyle=m.online?'rgba(160,255,221,.34)':'rgba(157,240,255,.28)'; ctx.lineWidth=1; ctx.stroke();
    globeHotspots.push({...m,hit:Math.max(12,aura*.72)});
  });
  globeRAF=requestAnimationFrame(drawClientGlobe)
}
function renderClientGlobe(){renderClientLocationList(); cancelAnimationFrame(globeRAF); hideGlobeTooltip(); ensureWorldLand(); globeRAF=requestAnimationFrame(drawClientGlobe)}
window.addEventListener('resize',()=>renderClientLocationList());
async function loadPresence(){const d=await api('/admin/presence');presenceSessions=d.sessions||[];renderClientGlobe();renderGhosts()}
function livePresence(){return presenceSessions.filter(p=>p&&!p.isAdmin&&p.online)}
function recentPresence(){return presenceSessions.filter(p=>p&&!p.isAdmin).sort((a,b)=>(new Date(b.lastSeenAt||0).getTime()||0)-(new Date(a.lastSeenAt||0).getTime()||0)).slice(0,10)}

function formatDuration(ms){ms=Math.max(0,Number(ms||0));const sec=Math.floor(ms/1000);if(sec<60)return`${sec}s`;const min=Math.floor(sec/60),s=sec%60;if(min<60)return`${min}m ${s}s`;const h=Math.floor(min/60),m=min%60;return`${h}h ${m}m`}
function ghostSessions(){return presenceSessions.filter(p=>p&&!p.isAdmin&&p.ghost===true).sort((a,b)=>(new Date(b.lastSeenAt||0).getTime()||0)-(new Date(a.lastSeenAt||0).getTime()||0))}
function ghostLabel(p){const id=String(p.visitorId||p.sessionId||p.id||'').replace(/^v_|^s_|^session_/, '');return`Fantasma #${(id.slice(-6)||'ANON').toUpperCase()}`}
function ghostPlace(p){const g=p.geo||{};return[g.city,g.region,g.country].filter(Boolean).filter((x,i,a)=>a.indexOf(x)===i).join(', ')||'Ubicación sin resolver'}
function renderGhosts(){const body=$('ghostsBody');if(!body)return;const all=ghostSessions();const online=all.filter(p=>p.online);const avg=all.length?all.reduce((sum,p)=>sum+Number(p.durationMs||0),0)/all.length:0;const views=all.reduce((sum,p)=>sum+Number(p.pageViews||p.journey?.length||0),0);$('gOnline').textContent=online.length;$('gSessions').textContent=all.length;$('gAvg').textContent=formatDuration(avg);$('gViews').textContent=views;const q=($('ghostSearch')?.value||'').toLowerCase(),state=$('ghostState')?.value||'';const list=all.filter(p=>{if(state==='online'&&!p.online)return false;if(state==='recent'&&p.online)return false;const hay=`${ghostLabel(p)} ${ghostPlace(p)} ${p.device||''} ${p.path||''} ${p.title||''} ${(p.journey||[]).map(x=>`${x.path} ${x.title}`).join(' ')}`.toLowerCase();return!q||hay.includes(q)});body.innerHTML=list.map(p=>{const j=Array.isArray(p.journey)?p.journey:[],last=j[j.length-1]||{},place=ghostPlace(p),route=j.slice(-4).map(x=>x.title||x.path).filter(Boolean).join(' → ')||'1 vista';return`<tr><td>${p.online?'<span class="ghost-online">En línea</span>':'<span class="ghost-offline">Reciente</span>'}</td><td><span class="ghost-badge"><i class="bi bi-incognito"></i> Fantasma</span><div style="margin-top:6px"><b>${esc(ghostLabel(p))}</b><div class="ghost-session-id">${esc(String(p.sessionId||'').slice(-18))}</div></div></td><td>${flag(p.geo?.countryCode)} <b>${esc(place)}</b><div class="muted">IP no almacenada</div></td><td><b>${sessionDeviceGlyph(sessionDeviceLabel(p))} ${esc(sessionDeviceLabel(p))}</b><div class="muted">${sessionDeviceMeta(p)}</div><div class="muted">${geoPill('browser',sessionBrowserLabel(p))}</div></td><td>${date(p.startedAt)}</td><td><b>${formatDuration(p.durationMs)}</b><div class="muted">${Number(p.pageViews||j.length||0)} vistas · ${Number(p.uniquePages||0)} únicas</div></td><td><div class="ghost-path"><b>${esc(last.title||p.title||'Dingloft')}</b><small>${esc(last.path||p.path||'/')}</small></div></td><td><div class="ghost-path"><b>${esc(route)}</b><small>${j.length} paso${j.length===1?'':'s'}</small></div></td><td><button class="btn small ghost-detail" data-id="${esc(p.id)}"><i class="bi bi-chevron-right"></i></button></td></tr>`}).join('')||'<tr><td colspan="9" class="empty">Todavía no hay visitantes fantasma registrados.</td></tr>';document.querySelectorAll('.ghost-detail').forEach(b=>b.onclick=()=>openGhost(presenceSessions.find(p=>p.id===b.dataset.id)))}
function openGhost(p){if(!p)return;activeGhost=p;const j=Array.isArray(p.journey)?p.journey:[];$('ghostModalSub').textContent=`${ghostLabel(p)} · ${ghostPlace(p)}`;$('ghostDetail').innerHTML=`<div class="formgrid"><div class="group"><label>Estado</label><div>${p.online?'<span class="ghost-online">En línea ahora</span>':'Reciente'}</div></div><div class="group"><label>Tiempo activo aproximado</label><div><b>${formatDuration(p.durationMs)}</b></div></div><div class="group"><label>Primera actividad</label><div>${date(p.startedAt)}</div></div><div class="group"><label>Última actividad</label><div>${date(p.lastSeenAt)}</div></div><div class="group"><label>Dispositivo</label><div>${sessionDeviceGlyph(sessionDeviceLabel(p))} ${esc(sessionDeviceLabel(p))} · ${sessionDeviceMeta(p)}<div class="geo-badges" style="margin-top:8px">${geoPill('device',sessionDeviceLabel(p))}${geoPill('browser',sessionBrowserLabel(p))}</div></div></div><div class="group"><label>Ubicación</label><div>${flag(p.geo?.countryCode)} ${esc(ghostPlace(p))}</div></div><div class="group full"><label>Identificador anónimo</label><div class="ghost-session-id">Visitante ${esc(p.visitorId||'—')}<br>Sesión ${esc(p.sessionId||'—')}</div></div></div><div class="ghost-journey">${j.length?j.map((x,i)=>`<div class="ghost-step"><div class="n">${i+1}</div><div><b>${esc(x.title||'Dingloft')}</b><small>${esc(x.path||'/')} · ${date(x.enteredAt)}</small></div><div class="t">${formatDuration(x.activeMs)}</div></div>`).join(''):'<div class="ghost-empty">No hay recorrido disponible todavía.</div>'}</div><div class="ghost-privacy"><i class="bi bi-shield-lock"></i> Este registro usa un identificador aleatorio del navegador y geolocalización aproximada de Cloudflare. No contiene la IP cruda ni ubicación GPS exacta.</div>`;$('ghostModal').classList.add('show')}
$('ghostSearch')?.addEventListener('input',renderGhosts);$('ghostState')?.addEventListener('change',renderGhosts);$('refreshGhosts')?.addEventListener('click',async()=>{try{await guardedLoad('presence',loadPresence);renderSyncHealth()}catch(_){}});

function renderMtMediaPreviews(){
  const cover=$('mtCover')?.value.trim()||''; const cp=$('mtCoverPreview'); if(cp) cp.innerHTML=cover?`<img src="${esc(cover)}" alt=""><div><b>Portada lista</b><div class="muted" style="font-size:10px;margin-top:4px">${esc(cover)}</div></div>`:'<span class="muted">Sin portada seleccionada</span>';
  const preview=$('mtPreview')?.value.trim()||''; const ap=$('mtAudioPreview'); if(ap) ap.innerHTML=preview?`<audio controls preload="metadata" playsinline src="${esc(preview)}"></audio>`:'<span class="muted">Sin preview de audio</span>';
  const ready=Boolean($('mtDelivery')?.value.trim()); const ds=$('mtDeliveryState'); if(ds){ds.classList.toggle('ready',ready);ds.textContent=ready?'Entrega configurada · checkout habilitable':'Sin archivo de entrega · venta protegida';}
}
function clearMultitrackEditor(){editingMultitrackId='';['mtId','mtTitle','mtArtist','mtPrice','mtBpm','mtChord','mtStems','mtCover','mtPreview','mtDelivery'].forEach(id=>{if($(id))$(id).value=''});$('mtTag').value='all';$('mtActive').checked=true;$('mtFeatured').checked=false;$('mtCoverFile').value='';$('mtPreviewFile').value='';status('mtAdminStatus','');renderMtMediaPreviews();renderMultitrackList();$('mtTitle')?.focus()}
function fillMultitrack(mt){if(!mt)return;editingMultitrackId=mt.id||'';$('mtId').value=mt.id||'';$('mtTitle').value=mt.title||'';$('mtArtist').value=mt.artist||'';$('mtPrice').value=Number(mt.priceUsd??mt.price??0);$('mtBpm').value=mt.bpm||'';$('mtChord').value=mt.chord||mt.key||'';$('mtStems').value=mt.stems||'';$('mtTag').value=mt.tag||'all';$('mtActive').checked=mt.active!==false;$('mtFeatured').checked=mt.featured===true;$('mtCover').value=mt.cover||'';$('mtPreview').value=mt.preview||'';$('mtDelivery').value=mt.deliveryUrl||'';renderMtMediaPreviews();renderMultitrackList()}
function renderMultitrackList(){const root=$('mtAdminList');if(!root)return;const q=($('mtAdminSearch')?.value||'').toLowerCase();const list=multitracks.filter(mt=>!q||`${mt.id} ${mt.title} ${mt.artist}`.toLowerCase().includes(q));root.innerHTML=list.map(mt=>`<div class="mt-admin-item ${editingMultitrackId===mt.id?'active':''}" data-id="${esc(mt.id)}"><img class="mt-admin-thumb" src="${esc(mt.cover||'/img/pwa-liquid-rounded-192-v17.png')}" onerror="this.src='/img/pwa-liquid-rounded-192-v17.png'"><div><b>${esc(mt.title)}</b><small>${esc(mt.id)} · ${esc(mt.artist)} · ${money(mt.priceUsd??mt.price)}</small></div><span class="pill ${mt.active!==false?'ok':'warn'}">${mt.active!==false?'Activo':'Oculto'}</span></div>`).join('')||'<div class="empty">No hay Multitracks.</div>';root.querySelectorAll('.mt-admin-item').forEach(el=>el.onclick=()=>fillMultitrack(multitracks.find(mt=>mt.id===el.dataset.id)))}
async function loadMultitracks(){const d=await api('/admin/multitracks/catalog');multitracks=d.multitracks||[];renderMultitrackList();if(editingMultitrackId){const mt=multitracks.find(x=>x.id===editingMultitrackId);if(mt)fillMultitrack(mt)}}
async function uploadMultitrackFile(kind){const input=$(kind==='cover'?'mtCoverFile':'mtPreviewFile');const file=input?.files?.[0];if(!file)throw Error(kind==='cover'?'Selecciona una portada primero.':'Selecciona un audio primero.');const max=kind==='cover'?8*1024*1024:60*1024*1024;if(file.size>max)throw Error(kind==='cover'?'La portada supera 8 MB.':'El preview supera 60 MB.');const u=auth.currentUser;if(!u)throw Error('Sesión no válida');const token=await u.getIdToken();status('mtAdminStatus',kind==='cover'?'Subiendo portada…':'Subiendo audio…','warn');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),90000);let r;try{r=await fetch(`${WORKER}/admin/multitracks/upload?kind=${encodeURIComponent(kind)}`,{method:'POST',signal:controller.signal,headers:{Authorization:`Bearer ${token}`,'content-type':file.type||'application/octet-stream','x-file-name':encodeURIComponent(file.name)},body:file})}finally{clearTimeout(timer)}const d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw Error(d.error||`Error ${r.status}`);$(kind==='cover'?'mtCover':'mtPreview').value=d.url||'';renderMtMediaPreviews();status('mtAdminStatus',kind==='cover'?'Portada subida.':'Audio subido.','ok')}
renderMtMediaPreviews();$('mtUploadCover').onclick=()=>uploadMultitrackFile('cover').catch(e=>status('mtAdminStatus',e.message,'bad'));$('mtUploadPreview').onclick=()=>uploadMultitrackFile('preview').catch(e=>status('mtAdminStatus',e.message,'bad'));$('mtCover').addEventListener('input',renderMtMediaPreviews);$('mtPreview').addEventListener('input',renderMtMediaPreviews);$('mtDelivery').addEventListener('input',renderMtMediaPreviews);$('mtAdminSearch').addEventListener('input',renderMultitrackList);$('newMultitrack').onclick=clearMultitrackEditor;
$('saveMultitrack').onclick=async()=>{try{const title=$('mtTitle').value.trim(),artist=$('mtArtist').value.trim();if(!title||!artist)throw Error('Título y artista son obligatorios.');status('mtAdminStatus','Guardando Multitrack…','warn');const d=await api('/admin/multitracks/upsert',{method:'POST',body:{id:$('mtId').value.trim(),title,artist,priceUsd:Number($('mtPrice').value||0),bpm:$('mtBpm').value.trim(),chord:$('mtChord').value.trim(),stems:$('mtStems').value.trim(),tag:$('mtTag').value,featured:$('mtFeatured').checked,active:$('mtActive').checked,cover:$('mtCover').value.trim(),preview:$('mtPreview').value.trim(),deliveryUrl:$('mtDelivery').value.trim()}});editingMultitrackId=d.id||d.multitrack?.id||editingMultitrackId;if(d.multitrack?.deliveryUrl)$('mtDelivery').value=d.multitrack.deliveryUrl;const kept=Boolean(d.multitrack?.deliveryUrl||$('mtDelivery').value.trim());status('mtAdminStatus',kept?'Guardado. Entrega preservada y lista para venta.':'Guardado en catálogo. Falta entrega final para cobrar.',kept?'ok':'warn');await loadMultitracks();const saved=multitracks.find(x=>x.id===editingMultitrackId);if(saved)fillMultitrack(saved)}catch(e){status('mtAdminStatus',e.message,'bad')}};

async function loadProducts(){const d=await api('/admin/products/catalog');products=d.products||[];renderProductList();refreshProductDatalists()}
function refreshProductDatalists(){document.querySelectorAll('.product-select').forEach(sel=>fillProductSelect(sel,sel.value))}
function renderProductList(){const q=($('productSearch')?.value||'').toLowerCase();$('productList').innerHTML=products.filter(p=>!q||`${p.name} ${p.sku} ${p.category}`.toLowerCase().includes(q)).map(p=>`<div class="pitem ${editingSku===p.sku?'active':''}" data-sku="${esc(p.sku)}"><div><b>${esc(p.name)}</b><small>${esc(p.category)} · ${money(p.priceUsd)}</small></div><span class="pill ${p.deliveryConfigured?'ok':'warn'}">${p.deliveryConfigured?'Listo':'Sin link'}</span></div>`).join('');document.querySelectorAll('.pitem').forEach(e=>e.onclick=()=>fillProduct(products.find(p=>p.sku===e.dataset.sku)))}$('productSearch').oninput=renderProductList;
function blankProduct(){editingSku='';['pName','pSku','pPrice','pCompare','pCategory','pType','pImage','pShort','pDescription','pBadge'].forEach(id=>$(id).value='');$('pActive').checked=true;$('pFeatured').checked=false;$('assets').innerHTML='';assetRow();$('previewProduct').removeAttribute('href');renderProductList()}
function assetRow(a={}){const r=document.createElement('div');r.className='asset-row asset';r.innerHTML=`<input class="field aname" placeholder="Nombre del archivo" value="${esc(a.name||'')}"><input class="field aurl" placeholder="https://drive.google.com/..." value="${esc(a.url||'')}"><button class="btn danger small" type="button"><i class="bi bi-trash"></i></button>`;r.querySelector('button').onclick=()=>r.remove();$('assets').appendChild(r)}$('addAsset').onclick=()=>assetRow();$('newProduct').onclick=blankProduct;
function fillProduct(p){if(!p)return;editingSku=p.sku;const vals={pName:p.name,pSku:p.sku,pPrice:p.priceUsd,pCompare:p.compareAtUsd,pCategory:p.category,pType:p.type,pImage:p.imageUrl||p.img,pShort:p.shortDescription,pDescription:p.description,pBadge:p.badge};Object.entries(vals).forEach(([k,v])=>$(k).value=v??'');$('pActive').checked=p.active!==false;$('pFeatured').checked=p.featured===true;$('assets').innerHTML='';(p.assets||[]).forEach(assetRow);if(!(p.assets||[]).length)assetRow();$('previewProduct').href=`producto.html?slug=${encodeURIComponent(p.sku)}`;renderProductList()}
$('pName').oninput=()=>{if(!editingSku)$('pSku').value=slug($('pName').value)};$('saveProduct').onclick=async()=>{try{const sku=slug($('pSku').value||$('pName').value),assets=[...document.querySelectorAll('.asset')].map((r,i)=>({name:r.querySelector('.aname').value.trim()||`Archivo ${i+1}`,url:r.querySelector('.aurl').value.trim()})).filter(a=>a.url);if(!sku||!$('pName').value.trim())throw Error('Nombre y SKU son obligatorios');const raw=$('pImage').value.trim(),isUrl=/^https?:\/\//i.test(raw);status('productStatus','Guardando…','warn');await api('/admin/products/upsert',{method:'POST',body:{sku,name:$('pName').value.trim(),priceUsd:Number($('pPrice').value||0),compareAtUsd:Number($('pCompare').value||0),category:$('pCategory').value.trim(),type:$('pType').value.trim(),img:isUrl?'dingloft':raw||'dingloft',imageUrl:isUrl?raw:'',shortDescription:$('pShort').value.trim(),description:$('pDescription').value.trim(),badge:$('pBadge').value.trim(),active:$('pActive').checked,featured:$('pFeatured').checked,assets}});editingSku=sku;status('productStatus',assets.length?'Guardado y listo para entregar.':'Guardado. El cobro se bloqueará hasta agregar un link.',assets.length?'ok':'warn');await loadProducts();fillProduct(products.find(p=>p.sku===sku));renderDashboard()}catch(e){status('productStatus',e.message,'bad')}};
async function loadOrders(){const d=await api('/admin/orders?limit=300');orders=d.orders||[];renderOrders()}
function payPill(s){return s==='paid'?'<span class="pill ok">Pagado</span>':'<span class="pill warn">Pendiente</span>'}function fulfillPill(s){return s==='ready'?'<span class="pill ok">Lista</span>':s==='revoked'?'<span class="pill bad">Revocada</span>':s==='hold'?'<span class="pill warn">En espera</span>':'<span class="pill info">Pendiente</span>'}
function renderOrders(){const q=$('orderSearch').value.toLowerCase(),pf=$('orderPaymentFilter').value,ff=$('orderFulfillFilter').value,list=orders.filter(o=>(!pf||o.paymentStatus===pf)&&(!ff||o.fulfillmentStatus===ff)&&(!q||`${o.orderNumber} ${o.userEmail} ${o.payerName} ${o.payerCountry} ${(o.items||[]).map(i=>i.name).join(' ')}`.toLowerCase().includes(q)));$('ordersBody').innerHTML=list.map(o=>`<tr><td><b>${esc(o.orderNumber)}</b><div class="muted">${esc(o.transactionId||o.paypalOrderId||'Manual')}</div></td><td><b>${esc(o.payerName||'Cliente')}</b><div class="muted">${esc(o.userEmail)}</div></td><td>${flag(o.payerCountryCode)} ${esc(o.payerCountry||'Sin registrar')}</td><td>${(o.items||[]).map(i=>`${Number(i.quantity||1)>1?`${i.quantity}× `:''}${esc(i.name)}`).join('<br>')}</td><td><b>${money(o.orderTotalUsd||o.amountPaidUsd)}</b></td><td>${payPill(o.paymentStatus)}</td><td>${fulfillPill(o.fulfillmentStatus)}</td><td>${date(o.createdAt)}</td><td><button class="btn small order-detail" data-id="${esc(o.purchaseId)}"><i class="bi bi-chevron-right"></i></button></td></tr>`).join('')||'<tr><td colspan="9" class="empty">No hay pedidos.</td></tr>';document.querySelectorAll('.order-detail').forEach(b=>b.onclick=()=>openOrder(orders.find(o=>o.purchaseId===b.dataset.id)))}['orderSearch','orderPaymentFilter','orderFulfillFilter'].forEach(id=>$(id).oninput=renderOrders);
function openOrder(o){activeOrder=o;$('orderDetail').innerHTML=`<div class="formgrid"><div class="group"><label>Orden</label><div>${esc(o.orderNumber)}</div></div><div class="group"><label>Total</label><div>${money(o.orderTotalUsd||o.amountPaidUsd)}</div></div><div class="group"><label>Cliente</label><div>${esc(o.payerName)}<br><span class="muted">${esc(o.userEmail)}</span></div></div><div class="group"><label>País</label><div>${flag(o.payerCountryCode)} ${esc(o.payerCountry||'Sin registrar')}</div></div><div class="group full"><label>Productos</label><div>${(o.items||[]).map(i=>`${Number(i.quantity||1)}× ${esc(i.name)} · ${money(i.priceUsd)}`).join('<br>')}</div></div><div class="group"><label>Pago</label><select id="odPayment" class="field"><option value="paid" ${o.paymentStatus==='paid'?'selected':''}>Pagado</option><option value="pending" ${o.paymentStatus==='pending'?'selected':''}>Pendiente</option></select></div><div class="group"><label>Entrega</label><select id="odFulfill" class="field"><option value="ready" ${o.fulfillmentStatus==='ready'?'selected':''}>Lista</option><option value="hold" ${o.fulfillmentStatus==='hold'?'selected':''}>En espera</option><option value="revoked" ${o.fulfillmentStatus==='revoked'?'selected':''}>Revocada</option><option value="pending_payment" ${o.fulfillmentStatus==='pending_payment'?'selected':''}>Pendiente de pago</option></select></div><div class="group full"><label>Nota interna</label><textarea id="odNote" class="field textarea">${esc(o.adminNote||'')}</textarea></div></div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:14px"><button class="btn primary" id="odSave">Guardar cambios</button><button class="btn" id="odEmail"><i class="bi bi-envelope"></i> Reenviar correo</button></div><div id="odStatus" class="statusmsg"></div>`;$('orderDetailModal').classList.add('show');$('odSave').onclick=async()=>{try{status('odStatus','Guardando…','warn');await api('/admin/orders/update',{method:'POST',body:{purchaseId:o.purchaseId,paymentStatus:$('odPayment').value,fulfillmentStatus:$('odFulfill').value,adminNote:$('odNote').value}});status('odStatus','Pedido actualizado.','ok');await loadOrders();renderDashboard();renderFinance()}catch(e){status('odStatus',e.message,'bad')}};$('odEmail').onclick=async()=>{try{status('odStatus','Enviando…','warn');await api('/admin/orders/resend-email',{method:'POST',body:{purchaseId:o.purchaseId}});status('odStatus','Correo enviado por Zoho.','ok')}catch(e){status('odStatus',e.message,'bad')}}}
async function loadCustomers(){const d=await api('/admin/customers');customers=d.customers||[];renderCustomers();$('customerList').innerHTML=customers.filter(c=>c.email).map(c=>`<option value="${esc(c.email)}">${esc(c.displayName||'')} · ${esc(c.nationality||'')}</option>`).join('');renderClientGlobe()}
function renderCustomers(){const q=$('customerSearch').value.toLowerCase(),cf=$('countryFilter').value;const countries=[...new Set(customers.map(c=>c.nationality).filter(Boolean))].sort();const old=cf;$('countryFilter').innerHTML='<option value="">Todas las nacionalidades</option>'+countries.map(c=>`<option ${c===old?'selected':''}>${esc(c)}</option>`).join('');const list=customers.filter(c=>(!cf||c.nationality===cf)&&(!q||`${c.email} ${c.displayName} ${c.nationality} ${c.lastPresenceDevice||''}`.toLowerCase().includes(q)));$('customersBody').innerHTML=list.map(c=>{const blocked=c.accountBlocked===true||c.accountReviewStatus==='under_review';const adminAccount=ADMIN.has(String(c.email||'').toLowerCase());const device=String(c.lastPresenceDevice||'Sin registrar');return `<tr><td><div class="clientcard"><img class="avatar" src="${esc(c.photoURL||`https://ui-avatars.com/api/?name=${encodeURIComponent(c.displayName||c.email||'D')}&background=17212d&color=fff`)}"><div><b>${esc(c.displayName||(c.email||'cliente').split('@')[0])}</b><div class="muted">${esc(c.email)}</div></div></div></td><td><span class="flag">${flag(c.nationalityCode)}</span>${esc(c.nationality||'Sin registrar')}</td><td><b>${c.ordersCount||0}</b></td><td>${c.itemsCount||0}</td><td><b>${money(c.totalSpentUsd)}</b></td><td>${date(c.lastPurchaseAt)}</td><td><b>${esc(device)}</b><div class="muted">${date(c.lastLogin)}</div></td><td><span class="access-pill ${blocked?'blocked':'active'}"><i class="bi ${blocked?'bi-shield-lock-fill':'bi-shield-check'}"></i>${blocked?'En revisión':'Activa'}</span></td><td class="muted">${esc((c.adminNote||'').slice(0,80))||'—'}</td><td><div class="customer-actions"><button class="btn small edit-customer" data-id="${esc(c.uid)}"><i class="bi bi-pencil"></i></button>${adminAccount?'':`<button class="btn small ${blocked?'':'danger'} toggle-block-row" data-id="${esc(c.uid)}" title="${blocked?'Desbloquear':'Bloquear'}"><i class="bi ${blocked?'bi-unlock':'bi-shield-lock'}"></i></button>`}</div></td></tr>`}).join('')||'<tr><td colspan="10" class="empty">No hay clientes.</td></tr>';document.querySelectorAll('.edit-customer').forEach(b=>b.onclick=()=>openCustomer(customers.find(c=>c.uid===b.dataset.id)));document.querySelectorAll('.toggle-block-row').forEach(b=>b.onclick=()=>toggleCustomerReview(customers.find(c=>c.uid===b.dataset.id)))}$('customerSearch').oninput=renderCustomers;$('countryFilter').onchange=renderCustomers;
function paintCustomerAccess(c){const blocked=c?.accountBlocked===true||c?.accountReviewStatus==='under_review';$('cReviewMessage').value=c?.accountReviewMessage||DEFAULT_REVIEW_MESSAGE;$('cAccessBox').innerHTML=blocked?'<b>Cuenta en revisión</b><br>El acceso a la cuenta, biblioteca, checkout y nuevas descargas está suspendido.':'<b>Acceso activo</b><br>El cliente puede usar su cuenta normalmente.';$('toggleCustomerBlock').innerHTML=blocked?'<i class="bi bi-unlock"></i> Desbloquear cuenta':'<i class="bi bi-shield-lock"></i> Bloquear cuenta';$('toggleCustomerBlock').classList.toggle('danger',!blocked);$('toggleCustomerBlock').disabled=ADMIN.has(String(c?.email||'').toLowerCase())}
function openCustomer(c){activeCustomer=c;$('cUid').value=c.uid;$('cEmail').value=c.email;$('cCode').value=c.nationalityCode||'';$('cNationality').value=c.nationality||'';$('cNote').value=c.adminNote||'';paintCustomerAccess(c);status('customerStatus','');$('customerModal').classList.add('show')}
async function toggleCustomerReview(c=activeCustomer){if(!c)return;const blocked=c.accountBlocked===true||c.accountReviewStatus==='under_review';if(!blocked&&!confirm(`¿Poner la cuenta de ${c.email||c.displayName||'este cliente'} en revisión?`))return;try{status('customerStatus',blocked?'Desbloqueando…':'Bloqueando cuenta…','warn');await api('/admin/customers/block',{method:'POST',body:{uid:c.uid,email:c.email,blocked:!blocked,reason:'Revisión administrativa por reporte de transacción o posible actividad irregular',message:$('cReviewMessage')?.value||c.accountReviewMessage||DEFAULT_REVIEW_MESSAGE}});status('customerStatus',blocked?'Cuenta desbloqueada.':'Cuenta bloqueada y puesta en revisión.','ok');await loadCustomers();activeCustomer=customers.find(x=>x.uid===c.uid)||null;if(activeCustomer)paintCustomerAccess(activeCustomer);renderDashboard()}catch(e){status('customerStatus',e.message,'bad')}}
$('toggleCustomerBlock').onclick=()=>toggleCustomerReview(activeCustomer);$('saveCustomer').onclick=async()=>{try{status('customerStatus','Guardando…','warn');await api('/admin/customers/update',{method:'POST',body:{uid:$('cUid').value,email:$('cEmail').value,nationalityCode:$('cCode').value.trim().toUpperCase(),nationality:$('cNationality').value.trim(),adminNote:$('cNote').value}});status('customerStatus','Cliente actualizado.','ok');await loadCustomers();setTimeout(()=>$('customerModal').classList.remove('show'),500)}catch(e){status('customerStatus',e.message,'bad')}};
function fillProductSelect(sel,value=''){sel.innerHTML='<option value="">Selecciona producto…</option>'+products.filter(p=>p.active!==false).map(p=>`<option value="${esc(p.sku)}" ${p.sku===value?'selected':''}>${esc(p.name)} · ${money(p.priceUsd)}${p.deliveryConfigured?'':' · SIN LINK'}</option>`).join('')}
function orderItemRow(data={}){const r=document.createElement('div');r.className='order-item';r.innerHTML=`<select class="field product-select"></select><input class="field qty" type="number" min="1" max="99" value="${data.quantity||1}" title="Cantidad"><input class="field unit" type="number" step="0.01" min="0" value="${Number(data.unitPriceUsd||0).toFixed(2)}" title="Precio unitario"><b class="line-total">$0.00</b><button class="btn danger small remove-item" type="button"><i class="bi bi-trash"></i></button>`;const sel=r.querySelector('.product-select');fillProductSelect(sel,data.sku||'');sel.onchange=()=>{const p=products.find(x=>x.sku===sel.value);if(p)r.querySelector('.unit').value=Number(p.priceUsd||0).toFixed(2);calcManual()};r.querySelector('.qty').oninput=calcManual;r.querySelector('.unit').oninput=calcManual;r.querySelector('.remove-item').onclick=()=>{r.remove();calcManual()};$('manualItems').appendChild(r);calcManual()}
function calcManual(){let subtotal=0;document.querySelectorAll('#manualItems .order-item').forEach(r=>{const q=Math.max(1,Number(r.querySelector('.qty').value||1)),u=Math.max(0,Number(r.querySelector('.unit').value||0)),line=q*u;subtotal+=line;r.querySelector('.line-total').textContent=money(line)});const type=$('discountType').value,val=Math.max(0,Number($('discountValue').value||0));let disc=type==='percent'?subtotal*Math.min(100,val)/100:type==='fixed'?Math.min(subtotal,val):0;$('mSubtotal').textContent=money(subtotal);$('mDiscount').textContent=`-${money(disc)}`;$('mTotal').textContent=money(Math.max(0,subtotal-disc))} $('addOrderItem').onclick=()=>orderItemRow();$('discountType').onchange=calcManual;$('discountValue').oninput=calcManual;
function openNewOrder(){
  $('mCustomer').value='';
  $('manualItems').innerHTML='';
  orderItemRow();
  $('discountType').value='none';
  $('discountValue').value=0;
  $('manualPaymentStatus').value='paid';
  $('manualProvider').value='admin-manual';
  $('manualNote').value='';
  $('manualSendEmail').checked=true;
  status('manualStatus','');
  calcManual();
  $('orderModal').classList.add('show');
}
$('newOrder').onclick=openNewOrder;$('newOrderTop').onclick=openNewOrder;
$('createManualOrder').onclick=async()=>{try{const email=$('mCustomer').value.trim(),items=[...document.querySelectorAll('#manualItems .order-item')].map(r=>({sku:r.querySelector('.product-select').value,quantity:Number(r.querySelector('.qty').value||1),unitPriceUsd:Number(r.querySelector('.unit').value||0)})).filter(i=>i.sku);if(!email||!items.length)throw Error('Selecciona cliente y al menos un producto.');status('manualStatus','Creando pedido…','warn');const d=await api('/admin/orders/manual-create',{method:'POST',body:{customerEmail:email,items,discountType:$('discountType').value,discountValue:Number($('discountValue').value||0),paymentStatus:$('manualPaymentStatus').value,paymentProvider:$('manualProvider').value,adminNote:$('manualNote').value,sendEmail:$('manualSendEmail').checked}});status('manualStatus',`Pedido ${d.orderNumber} creado. Total ${money(d.totalUsd)}.`,'ok');await Promise.all([loadOrders(),loadCustomers()]);renderDashboard();renderFinance();setTimeout(()=>$('orderModal').classList.remove('show'),800)}catch(e){status('manualStatus',e.message,'bad')}};

async function purgeResolvedJuniorReviews(){
  const key='dingloft_resolved_review_cleanup_juniorromero098_v1';
  if(localStorage.getItem(key)==='done')return;
  try{
    const d=await api('/admin/reviews/purge-user',{method:'POST',body:{username:'juniorromero098'}});
    localStorage.setItem(key,'done');
    if(Number(d.deleted||0)>0)toast(`Se eliminaron ${Number(d.deleted)} reseña(s) resueltas de juniorromero098`);
  }catch(e){console.warn('review cleanup pending',e?.message||e)}
}
async function loadReviews(){
  try{
    const d=await api('/admin/reviews?limit=200');
    reviews=Array.isArray(d.reviews)?d.reviews:[];
    const products=[...new Set(reviews.map(r=>r.product).filter(Boolean))].sort();
    $('reviewProductFilter').innerHTML='<option value="">Todos los productos</option>'+products.map(p=>`<option value="${esc(p)}">${esc(p)}</option>`).join('');
    renderReviews();
  }catch(e){
    $('reviewsBody').innerHTML=`<tr><td colspan="7" class="empty">${esc(e.message||'No se pudieron cargar las reseñas.')}</td></tr>`;
  }
}
function stars(n){n=Math.max(1,Math.min(5,Number(n||5)));return '★'.repeat(n)+'☆'.repeat(5-n)}
function renderReviews(){
  const term=($('reviewSearch')?.value||'').trim().toLowerCase();
  const product=$('reviewProductFilter')?.value||'';
  const rows=reviews.filter(r=>{
    const hay=`${r.product||''} ${r.name||''} ${r.text||''}`.toLowerCase();
    return (!term||hay.includes(term))&&(!product||r.product===product);
  });
  $('reviewsBody').innerHTML=rows.length?rows.map(r=>`<tr>
    <td><b>${esc(r.product||'Producto')}</b><div class="muted" style="font-size:10px;margin-top:4px">${esc(r.collection||'')}</div></td>
    <td><b>${esc(r.name||'Usuario')}</b></td>
    <td style="max-width:480px;white-space:normal;line-height:1.45">${esc(r.text||'')}</td>
    <td><span style="color:#ffc857;letter-spacing:.04em">${stars(r.rating)}</span></td>
    <td>${Number(r.likes||0)}</td>
    <td>${date(r.createdAt)}</td>
    <td><button class="btn danger small review-delete" data-id="${esc(r.id)}" data-collection="${esc(r.collection)}" data-name="${esc(r.name||'Usuario')}"><i class="bi bi-trash"></i> Eliminar</button></td>
  </tr>`).join(''):'<tr><td colspan="7"><div class="empty">No hay reseñas que coincidan.</div></td></tr>';
  document.querySelectorAll('.review-delete').forEach(btn=>btn.onclick=async()=>{
    const label=btn.dataset.name||'este usuario';
    if(!confirm(`¿Eliminar esta reseña de ${label}?\n\nDesaparecerá de la página pública.`))return;
    const old=btn.innerHTML;btn.disabled=true;btn.innerHTML='<i class="bi bi-arrow-repeat"></i> Eliminando…';
    try{
      await api('/admin/reviews/delete',{method:'POST',body:{collection:btn.dataset.collection,id:btn.dataset.id}});
      reviews=reviews.filter(r=>!(r.collection===btn.dataset.collection&&r.id===btn.dataset.id));
      renderReviews();toast('Reseña eliminada');
    }catch(e){btn.disabled=false;btn.innerHTML=old;toast(e.message||'No se pudo eliminar')}
  });
}
$('reviewSearch').oninput=renderReviews;$('reviewProductFilter').onchange=renderReviews;$('refreshReviews').onclick=loadReviews;
function renderFinance(){const paid=orders.filter(o=>o.paymentStatus==='paid'),rev=paid.reduce((s,o)=>s+Number(o.amountPaidUsd||0),0),aov=paid.length?rev/paid.length:0,now=new Date(),month=paid.filter(o=>{const d=new Date(o.createdAt);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()}).reduce((s,o)=>s+Number(o.amountPaidUsd||0),0);$('fRevenue').textContent=money(rev);$('fAov').textContent=money(aov);$('fMonth').textContent=money(month);const map={};paid.forEach(o=>(o.items||[]).forEach(i=>{const k=i.name||i.sku;map[k]=(map[k]||0)+Number(i.quantity||1)}));const top=Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,10);$('topProducts').innerHTML=top.map(([n,c],i)=>`<div style="display:flex;justify-content:space-between;padding:9px 0;border-bottom:1px solid rgba(255,255,255,.05)"><span>${i+1}. ${esc(n)}</span><b>${c} ventas</b></div>`).join('')||'<div class="empty">Sin datos todavía.</div>'}
async function loadReservations(){try{const snap=await getDocs(collection(db,'reservas'));reservations=snap.docs.map(d=>({id:d.id,...d.data()}));renderReservations()}catch(e){$('reservationsList').innerHTML='<div class="empty">No se pudieron cargar las reservas.</div>'}}
function renderReservations(){$('reservationsList').innerHTML=reservations.length?reservations.map(r=>`<div class="reservation"><div class="reservation-top"><div><b>${esc(r.email||r.nombre||'Cliente')}</b><div class="muted">${esc(r.software||r.producto||'Servicio remoto')}</div></div><span class="pill ${r.estado==='completado'?'ok':'warn'}">${esc(r.estado||'pendiente')}</span></div><div class="reservation-grid"><div><small>Fecha</small><b>${esc(r.fecha||r.date||'—')}</b></div><div><small>Hora</small><b>${esc(r.hora||r.time||'—')}</b></div><div><small>Precio</small><b>${money(r.precio||r.price||0)}</b></div><div><small>Código</small><b>${esc(r.codigo||r.code||'—')}</b></div></div><div style="display:flex;gap:8px;margin-top:11px">${r.estado!=='completado'?`<button class="btn small res-done" data-id="${esc(r.id)}">Completar</button>`:''}<button class="btn danger small res-del" data-id="${esc(r.id)}">Eliminar</button></div></div>`).join(''):'<div class="empty">No hay reservas.</div>';document.querySelectorAll('.res-done').forEach(b=>b.onclick=async()=>{await updateDoc(doc(db,'reservas',b.dataset.id),{estado:'completado'});await loadReservations()});document.querySelectorAll('.res-del').forEach(b=>b.onclick=async()=>{if(confirm('¿Eliminar reserva?')){await deleteDoc(doc(db,'reservas',b.dataset.id));await loadReservations()}})}
$('refreshAll').onclick=async()=>{toast('Actualizando…');try{await loadAll();toast(Object.keys(loadErrors).length?'Panel actualizado con avisos':'Panel actualizado')}catch(e){toast(e.message||'No se pudo actualizar')}};$('logout').onclick=()=>signOut(auth);onAuthStateChanged(auth,async u=>{
  if(!u){location.href='login.html';return}
  const email=String(u.email||'').toLowerCase();
  if(!ADMIN.has(email)){location.href='account.html';return}
  $('adminEmail').textContent=email;$('adminName').textContent=email==='tepaz2025@gmail.com'?'Antonio · Admin':'César · Admin';
  hideAdminIntro();
  // Nunca bloquear el panel por limpiezas/tareas secundarias.
  loadAll().catch(e=>{console.error('Admin loadAll',e);renderSyncHealth();toast(e?.message||'No se pudo sincronizar el panel')});
  purgeResolvedJuniorReviews().catch(()=>{});
  const h=location.hash.replace('#','');if(h&&$(`view-${h}`))showView(h);
});blankProduct();
