(() => {
'use strict';
const DESKTOP=matchMedia('(min-width:900px) and (pointer:fine)').matches;
const q=new URLSearchParams(location.search);
if(!DESKTOP){const src=q.get('src')||'index.html';location.replace(src);return;}
const stage=document.getElementById('stage'),progress=document.getElementById('progress');let active=null,seq=0;const installed=matchMedia('(display-mode: standalone)').matches||navigator.standalone===true||Boolean(localStorage.getItem('dingloft_installed_at'));document.documentElement.classList.toggle('dingloft-installed',installed);if(installed)document.getElementById('navInstall')?.remove();addEventListener('appinstalled',()=>{localStorage.setItem('dingloft_installed_at',String(Date.now()));document.getElementById('navInstall')?.remove()});
const salesFiles=new Set(['ventas.html','tienda.html','multitrack.html','autocad.html','cinema4d.html','dual.html','esword.html','logic.html','mainstage.html','nord.html','office.html','producto.html','rhodes.html','sketchup.html','yamahakeys.html']);
function cleanSrc(raw){try{const u=new URL(raw||'index.html',location.origin);if(u.origin!==location.origin)return'';let file=u.pathname.split('/').filter(Boolean).pop()||'index.html';if(!/\./.test(file))file+='.html';if(!/^[A-Za-z0-9_.-]+\.html$/i.test(file))return'';if(file.toLowerCase()==='desktop-shell.html')return'index.html';u.searchParams.set('embed','desktop');return `${file}${u.search}${u.hash}`;}catch(_){return''}}
function publicSrc(src){return src.replace(/([?&])embed=desktop&?/,'$1').replace(/[?&]embed=desktop(?=#|$)/,'').replace(/\?$/,'')}
function shellUrl(src){const u=new URL('/desktop-shell.html',location.origin);u.searchParams.set('src',publicSrc(src));return `${u.pathname}${u.search}`}
function classify(src){try{const u=new URL(src,location.origin);const file=(u.pathname.split('/').pop()||'index.html').toLowerCase();return{sales:salesFiles.has(file),account:file==='account.html',install:file==='index.html'&&u.hash.toLowerCase()==='#instalar'};}catch(_){return{}}}
function paint(src){const c=classify(src);document.getElementById('navSales')?.classList.toggle('active',!!c.sales);document.getElementById('navAccount')?.classList.toggle('active',!!c.account);document.getElementById('navInstall')?.classList.toggle('active',!!c.install)}
function mapHref(href,base){let u;try{u=new URL(href,base)}catch(_){return null}if(u.origin!==location.origin)return null;const current=new URL(base);if(u.pathname===current.pathname&&u.search===current.search&&u.hash&&u.hash!==current.hash)return{hashOnly:true,url:u.href};let file=u.pathname.split('/').filter(Boolean).pop()||'index.html';if(!/\./.test(file))file+='.html';if(!/^[A-Za-z0-9_.-]+\.html$/i.test(file))return null;if(file.toLowerCase()==='desktop-shell.html')file='index.html';return{src:`${file}${u.search}${u.hash}`}}
function prepare(frame){try{const w=frame.contentWindow,d=w.document;d.documentElement.classList.add('dingloft-desktop-shell-view');d.body?.classList.add('dingloft-desktop-shell-view');if(!d.getElementById('dl-desktop-shell-style')){const s=d.createElement('style');s.id='dl-desktop-shell-style';s.textContent=`@media(min-width:900px) and (pointer:fine){html.dingloft-desktop-shell-view,html.dingloft-desktop-shell-view body{overscroll-behavior-x:auto!important}html.dingloft-desktop-shell-view body{padding-top:0!important}html.dingloft-desktop-shell-view #dingloftDesktopGlobalNav,html.dingloft-desktop-shell-view .topbar,html.dingloft-desktop-shell-view .navbar-glass,html.dingloft-desktop-shell-view nav.navbar.fixed-top{display:none!important}html.dingloft-desktop-shell-view body.dgn-offset-page{padding-top:0!important}html.dingloft-desktop-shell-view body.dgn-offset-page .sidebar{top:0!important;height:100vh!important}html.dingloft-desktop-shell-view body.dgn-offset-page .app,html.dingloft-desktop-shell-view body.dgn-offset-page .content{min-height:100vh!important}.tabs-header,.mt-filters,.mt-chip-row,.filter-row,.category-scroll,.product-tabs,.nav-pills,.horizontal-scroll,.table-scroll,.cards-scroll{overscroll-behavior-x:contain!important;-webkit-overflow-scrolling:touch!important}}`;d.head.appendChild(s)}
if(!d.__dingloftDesktopBridge){d.__dingloftDesktopBridge=1;d.addEventListener('click',e=>{const a=e.target instanceof w.Element?e.target.closest('a[href]'):null;if(!a||a.target==='_blank'||a.hasAttribute('download')||a.getAttribute('href')?.startsWith('mailto:')||a.getAttribute('href')?.startsWith('tel:'))return;const m=mapHref(a.getAttribute('href'),w.location.href);if(!m)return;if(m.hashOnly)return;e.preventDefault();e.stopPropagation();navigate(m.src,{push:true})},true)}if(!w.__dlDesktopInteraction){w.__dlDesktopInteraction=1;['gesturestart','gesturechange','gestureend'].forEach(type=>d.addEventListener(type,e=>e.preventDefault(),{passive:false}));w.addEventListener('wheel',e=>{if(e.ctrlKey){e.preventDefault();return}let rail=e.target instanceof w.Element?e.target.closest('[data-horizontal-scroll],.tabs-header,.mt-filters,.mt-chip-row,.filter-row,.category-scroll,.product-tabs,.nav-pills,.horizontal-scroll,.table-scroll,.cards-scroll'):null;if(!rail){let n=e.target instanceof w.Element?e.target:null;while(n&&n!==d.body){if(n.scrollWidth>n.clientWidth+4){rail=n;break}n=n.parentElement}}if(!rail||rail.scrollWidth<=rail.clientWidth+4)return;const intent=Math.abs(e.deltaX)>1||(e.shiftKey&&Math.abs(e.deltaY)>1);if(!intent)return;const delta=Math.abs(e.deltaX)>1?e.deltaX:e.deltaY;const before=rail.scrollLeft;rail.scrollLeft+=delta;if(rail.scrollLeft!==before)e.preventDefault()},{passive:false});w.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&['+','=','-','0'].includes(e.key))e.preventDefault()},{passive:false})}
const t=(d.title||'').trim();if(t)document.title=t.includes('Dingloft')?t:`${t} · Dingloft`;
}catch(_){}}
function navigate(raw,opt={}){const src=cleanSrc(raw);if(!src)return;const id=++seq;progress?.classList.add('show');paint(src);const f=document.createElement('iframe');f.className='frame';f.allow='payment *; clipboard-read; clipboard-write';f.src=src;stage.appendChild(f);f.addEventListener('load',()=>{if(id!==seq){f.remove();return}prepare(f);requestAnimationFrame(()=>f.classList.add('active'));const old=active;active=f;if(old&&old!==f){old.classList.add('out');setTimeout(()=>old.remove(),220)}progress?.classList.remove('show')},{once:true});if(!opt.pop){const url=shellUrl(src);if(opt.replace)history.replaceState({src:publicSrc(src)},'',url);else if(opt.push!==false)history.pushState({src:publicSrc(src)},'',url)}}
document.addEventListener('click',e=>{const a=e.target.closest?.('[data-shell-link]');if(!a)return;e.preventDefault();navigate(a.getAttribute('href'),{push:true})});
addEventListener('message',e=>{if(e.origin!==location.origin||!e.data)return;if(e.data.type==='dingloft:desktop-navigate')navigate(e.data.src||'index.html',{push:true})});
addEventListener('popstate',()=>{const p=new URLSearchParams(location.search);navigate(p.get('src')||'index.html',{pop:true,push:false})});
const initial=q.get('src')||'index.html';history.replaceState({src:initial},'',shellUrl(initial));navigate(initial,{replace:true,push:false});
})();